# Apague qualquer linha que contenha apenas "Retro"
# font_family      "Press Start 2P"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

# BEGIN_KITTY_FONTS
font_family      family="Terminess Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

disable_ligatures always
modify_font cell_height 100%

background #000000
foreground #aaaaaa

cursor #ffffff
cursor_shape block
shell_integration  disabled
# END_KITTY_FONTS
